#load packages

library(stats)
library(ade4)
library(ape)
library(BiocManager)
library(phangorn)
library(TransPhylo)
library(coda)
library(data.table)
library(ggtree)
library(lubridate)
library(phytools)
library(prevalence)
library(tidyverse)
library(sf)
library(raster)
library(RColorBrewer)
library(conflicted)
library(treeio)
library(transformr)
library(magick)
library(visNetwork)
library(igraph)
library(zoo)
library(xlsx)
require(tidygraph)
require(ggraph)

#specify package preferences
conflict_prefer("select", "dplyr")
conflict_prefer("drop.tip", "ape")
conflict_prefer("filter", "dplyr")
conflict_prefer("month", "lubridate")
conflict_prefer("isoweek", "lubridate")
conflict_prefer("year", "lubridate")

